# Generated by Django 5.2.5 on 2025-10-05 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('cedule', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=255)),
                ('tlf_princimal', models.IntegerField()),
                ('tlf_secundario', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='TProcesos',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Proceso',
                'verbose_name_plural': 'Tipos de Procesos',
                'db_table': 'tprocesos',
            },
        ),
        migrations.CreateModel(
            name='TUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuarios',
                'db_table': 'tusuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=65)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id_mencion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.carrera')),
            ],
            options={
                'verbose_name': 'Mención',
                'verbose_name_plural': 'Menciones',
                'db_table': 'mencion',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField(auto_now_add=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('periodo_cierre', models.DateField(blank=True, null=True)),
                ('acreditacion', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_mencion', models.ForeignKey(db_column='id_mencion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.mencion')),
                ('id_persona', models.ForeignKey(db_column='id_persona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.persona')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'expediente',
            },
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('aprobado', models.IntegerField(blank=True, null=True)),
                ('verficado', models.BooleanField(default=False)),
                ('anexo', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.expediente')),
                ('tproceso', models.ForeignKey(db_column='tproceso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tprocesos')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'db_table': 'procesos',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_usuario',
            field=models.ForeignKey(db_column='tipo_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion.tusuario'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.carrera')),
                ('id_persona', models.ForeignKey(db_column='id_persona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.persona')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutor',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='id_tutor',
            field=models.ForeignKey(db_column='id_tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tutor'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario'),
        ),
    ]
