# Generated by Django 5.2.5 on 2025-10-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mencion',
            name='id_carrera',
            field=models.ForeignKey(db_column='id_carrera', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.carrera'),
        ),
    ]
