# Generated by Django 5.2.5 on 2025-10-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_mencion_id_carrera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TUsuario',
            new_name='Tsuario',
        ),
        migrations.AlterModelTable(
            name='tsuario',
            table='tsuario',
        ),
    ]
