# Generated by Django 5.2.5 on 2025-10-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_tusuario_tsuario_alter_tsuario_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tsuario',
            new_name='Tusuario',
        ),
        migrations.AlterModelTable(
            name='tusuario',
            table='tusuario',
        ),
    ]
