# Generated by Django 5.2.5 on 2025-10-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_tsuario_tusuario_alter_tusuario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuario'},
        ),
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
