# Generated by Django 5.2.4 on 2025-10-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_usuario_options_persona_ciudad_persona_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tlf_secundario',
            field=models.IntegerField(null=True),
        ),
    ]
