# Generated by Django 5.2.4 on 2025-10-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_persona_tlf_secundario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tlf_princimal',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tlf_secundario',
            field=models.CharField(null=True),
        ),
    ]
