# Generated by Django 5.2.5 on 2025-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.AddField(
            model_name='expediente',
            name='asistencia',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Constancia de Asistencia'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='const_inscripcion',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Constancia de Inscripción'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='const_notas',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Constancia de Notas'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='doc_identidad',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='forma_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Formulario 1'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de Perfil'),
        ),
    ]
