# Generated by Django 5.2.5 on 2025-10-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_delete_documento_expediente_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cpostal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nucleo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
