# Generated by Django 5.2.5 on 2025-10-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_persona_cpostal_persona_nucleo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nucleo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
