# Generated by Django 5.2.5 on 2025-10-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_persona_nucleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estado',
            field=models.CharField(default='En Proceso', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id_carrera',
            field=models.ForeignKey(db_column='id_mencion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.mencion'),
        ),
    ]
