# Generated by Django 5.2.5 on 2025-10-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_expediente_estado_alter_tutor_id_carrera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='id_carrera',
            new_name='id_mencion',
        ),
    ]
