# Generated by Django 5.2.5 on 2025-10-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_rename_id_carrera_tutor_id_mencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='id_mencion',
            new_name='id_carrera',
        ),
    ]
