# Generated by Django 5.2.5 on 2025-10-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_rename_id_mencion_tutor_id_carrera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tprocesos',
            old_name='id_proceso',
            new_name='id_tproceso',
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='verficado',
        ),
        migrations.AddField(
            model_name='procesos',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=55),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='anexo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Anexo 1'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='aprobado',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='tproceso',
            field=models.ForeignKey(db_column='id_tproceso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tprocesos'),
        ),
    ]
