# Generated by Django 5.2.5 on 2025-10-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_rename_id_proceso_tprocesos_id_tproceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
