# Generated by Django 5.2.5 on 2025-10-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_procesos_aprobado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procesos',
            old_name='tproceso',
            new_name='id_tproceso',
        ),
    ]
