# Generated by Django 5.2.5 on 2025-11-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_rename_tproceso_procesos_id_tproceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='asistencia',
            field=models.FileField(blank=True, null=True, upload_to='recaudos/', verbose_name='Constancia de Asistencia'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='const_inscripcion',
            field=models.FileField(blank=True, null=True, upload_to='recaudos/', verbose_name='Constancia de Inscripción'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='const_notas',
            field=models.FileField(blank=True, null=True, upload_to='recaudos/', verbose_name='Constancia de Notas'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='doc_identidad',
            field=models.ImageField(blank=True, null=True, upload_to='recaudos/', verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='forma_1',
            field=models.FileField(blank=True, null=True, upload_to='recaudos/', verbose_name='Formulario 1'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='recaudos/', verbose_name='Foto de Perfil'),
        ),
    ]
