from django.db import models
from django.contrib.auth.models import User

# Modelo para usuario
class Usuario(models.Model):
    # id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY   
    id_usuario = models.AutoField(primary_key=True)
    
    usuario = models.CharField(max_length=100, unique=True) # usuario VARCHAR(100) NOT NULL UNIQUE
    clave = models.CharField(max_length=65) # clave VARCHAR(65) NOT NULL
    fecha_registro = models.DateTimeField(auto_now_add=True) # fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

    class Meta:
        db_table = 'usuario'
        verbose_name = "Usuario"
        verbose_name_plural = "Usuario"


    def __str__(self):
        return self.usuario

# ---------------------------------------------------------------------

# Modelo para tusuario
class Tusuario(models.Model):
    # id_tipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    id_tipo = models.AutoField(primary_key=True)
    
    nombre = models.CharField(max_length=50) # nombre VARCHAR (50)
    descripcion = models.TextField(blank=True, null=True) # descripcion TEXT
    fecha_registro = models.DateTimeField(auto_now_add=True) # fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

    class Meta:
        db_table = 'tusuario'
        verbose_name = "Tipo de Usuario"
        verbose_name_plural = "Tipos de Usuarios"

    def __str__(self):
        return self.nombre

# ---------------------------------------------------------------------

# Modelo para persona
class Persona(models.Model):
    # id_persona INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    id_persona = models.AutoField(primary_key=True)
    
    # FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario) ON DELETE CASCADE
    # NOTA: ON DELETE CASCADE no requiere null=True
    id_usuario = models.ForeignKey(
        Usuario, 
        on_delete=models.CASCADE, 
        db_column='id_usuario' # Mantiene el nombre de la columna en la DB
    )
    
    cedule = models.IntegerField(unique=True) # cedule INT NOT NULL UNIQUE
    nombre = models.CharField(max_length=255) # nombre VARCHAR(255)
    apellido = models.CharField(max_length=255) # apellido VARCHAR(255)
    fecha_nacimiento = models.DateField() # fecha_nacimiento date 
    correo = models.CharField(max_length=255) # correo VARCHAR(255)
    tlf_princimal = models.CharField() # tlf_princimal INT
    tlf_secundario = models.CharField(null=True) # tlf_secundario INT
    estado = models.CharField(max_length=255, null=True) # nombre VARCHAR(255)
    ciudad = models.CharField(max_length=255,blank=True , null=True) # apellido VARCHAR(255)
    cpostal = models.IntegerField(blank=True, null=True) # cpostal INT
    nucleo = models.CharField(max_length=255, null=True, blank=True) # nombre VARCHAR(255)
    # FOREIGN KEY (tipo_usuario) REFERENCES tusuario (id_tipo) ON DELETE SET NULL
    # NOTA: ON DELETE SET NULL requiere null=True
    tipo_usuario = models.ForeignKey(
        Tusuario, 
        on_delete=models.CASCADE, 
        db_column='tipo_usuario' # Mantiene el nombre de la columna en la DB
    )
    
    fecha_creacion = models.DateTimeField(auto_now_add=True) # fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP

    class Meta:
        db_table = 'persona'
        verbose_name = "Persona"
        verbose_name_plural = "Personas"

    def __str__(self):
        return f"{self.nombre} {self.apellido} ({self.cedule}) {self.tipo_usuario.nombre}"

# ---------------------------------------------------------------------

# Modelo para carrera
class Carrera(models.Model):
    # id_carrera INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    id_carrera = models.AutoField(primary_key=True)
    
    nombre = models.CharField(max_length=50) # nombre VARCHAR (50)
    descripcion = models.TextField(blank=True, null=True) # descripcion TEXT
    fecha_registro = models.DateTimeField(auto_now_add=True) # fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

    class Meta:
        db_table = 'carrera'
        verbose_name = "Carrera"
        verbose_name_plural = "Carreras"

    def __str__(self):
        return self.nombre

# ---------------------------------------------------------------------

# Modelo para mencion
class Mencion(models.Model):
    # id_mencion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    id_mencion = models.AutoField(primary_key=True)
    
    # FOREIGN KEY (id_carrera) REFERENCES carrera (id_carrera) ON DELETE SET NULL
    # Aunque tu SQL dice NOT NULL, el ON DELETE SET NULL obliga a null=True en Django.
    id_carrera = models.ForeignKey(
        Carrera, 
        on_delete=models.CASCADE, 
        db_column='id_carrera', 
        null=True 
    )
    
    nombre = models.CharField(max_length=50) # nombre VARCHAR (50)
    descripcion = models.TextField(blank=True, null=True) # descripcion TEXT
    fecha_registro = models.DateTimeField(auto_now_add=True) # fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

    class Meta:
        db_table = 'mencion'
        verbose_name = "Mención"
        verbose_name_plural = "Menciones"

    def __str__(self):
        return self.nombre

# ---------------------------------------------------------------------

# Modelo para tutor
class Tutor(models.Model):
    # id_tutor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    id_tutor = models.AutoField(primary_key=True)
    
    # FOREIGN KEY (id_persona) REFERENCES persona (id_persona) ON DELETE SET NULL
    id_persona = models.ForeignKey(
        Persona, 
        on_delete=models.SET_NULL, 
        db_column='id_persona',
        null=True 
    )
    
    # FOREIGN KEY (id_carrera) REFERENCES carrera (id_carrera) ON DELETE SET NULL
    id_carrera = models.ForeignKey(
        Mencion, 
        on_delete=models.SET_NULL, 
        db_column='id_mencion',
        null=True 
    )
    
    fecha_registro = models.DateTimeField(auto_now_add=True) # fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

    class Meta:
        db_table = 'tutor'
        verbose_name = "Tutor"
        verbose_name_plural = "Tutores"

    def __str__(self):
        return f"{self.id_persona.nombre if self.id_persona else 'N/A'} {self.id_persona.apellido if self.id_persona else 'N/A'} {self.id_carrera.nombre}" 

# ---------------------------------------------------------------------

# Modelo para expediente
class Expediente(models.Model):
    # id_expediente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    id_expediente = models.AutoField(primary_key=True)
    
    # FOREIGN KEY (id_persona) REFERENCES persona (id_persona) ON DELETE SET NULL
    id_persona = models.ForeignKey(
        Persona, 
        on_delete=models.SET_NULL, 
        db_column='id_persona',
        null=True 
    )
    
    # FOREIGN KEY (id_tutor) REFERENCES tutor (id_tutor) ON DELETE SET NULL
    id_tutor = models.ForeignKey(
        Tutor, 
        on_delete=models.SET_NULL, 
        db_column='id_tutor',
        null=True 
    )
    
    # FOREIGN KEY (id_mencion) REFERENCES mencion (id_mencion) ON DELETE SET NULL
    id_mencion = models.ForeignKey(
        Mencion, 
        on_delete=models.SET_NULL, 
        db_column='id_mencion',
        null=True 
    )
    
    periodo_inicio = models.DateField(auto_now_add=True) # periodo_inicio DATE
    periodo_fin = models.DateField(blank=True, null=True) # periodo_fin DATE
    periodo_cierre = models.DateField(blank=True, null=True) # periodo_cierre DATE
    acreditacion = models.BooleanField(default=False) # acreditacion BOOLEAN
    fecha_registro = models.DateTimeField(auto_now_add=True) # fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    doc_identidad  = models.ImageField('Cédula', blank=True, null=True, upload_to='recaudos/')
    foto_perfil = models.ImageField('Foto de Perfil', blank=True, null=True, upload_to='recaudos/')
    const_notas = models.FileField('Constancia de Notas', blank=True, null=True, upload_to='recaudos/')
    const_inscripcion = models.FileField('Constancia de Inscripción', blank=True, null=True, upload_to='recaudos/')
    asistencia = models.FileField('Constancia de Asistencia', blank=True, null=True, upload_to='recaudos/')
    forma_1 = models.FileField('Formulario 1', blank=True, null=True, upload_to='recaudos/')
    estado = models.CharField(max_length=50, default='En Proceso') # estado VARCHAR(50)
    class Meta:
        db_table = 'expediente'
        verbose_name = "Expediente"
        verbose_name_plural = "Expedientes"

    def __str__(self):
        return f"Expediente #{self.id_expediente} {self.doc_identidad}"

# ---------------------------------------------------------------------

# Modelo para t
# 
# 
# esos
class TProcesos(models.Model):
    # id_proceso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    id_tproceso = models.AutoField(primary_key=True)
    
    nombre = models.CharField(max_length=50) # nombre VARCHAR(50)
    fecha_registro = models.DateTimeField(auto_now_add=True) # fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

    class Meta:
        db_table = 'tprocesos'
        verbose_name = "Tipo de Proceso"
        verbose_name_plural = "Tipos de Procesos"

    def __str__(self):
        return self.nombre

# ---------------------------------------------------------------------

# Modelo para procesos
class Procesos(models.Model):
    # id_proceso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (del proceso)
    id_proceso = models.AutoField(primary_key=True) 
    
    # FOREIGN KEY (id_expediente) REFERENCES expediente (id_expediente) ON DELETE SET NULL
    id_expediente = models.ForeignKey(
        Expediente, 
        on_delete=models.SET_NULL, 
        db_column='id_expediente',
        null=True 
    )
    
    # FOREIGN KEY (tproceso) REFERENCES tprocesos (id_proceso) ON DELETE SET NULL
    id_tproceso = models.ForeignKey(
        TProcesos, 
        on_delete=models.SET_NULL, 
        db_column='id_tproceso',
        null=True 
    )
    
    aprobado = models.BooleanField(default=False) # BOOLEAN
    estado = models.CharField(max_length=55, default="Pendiente") # verficado BOOLEAN
    anexo = models.ImageField('Anexo 1', blank=True, null=True) # anexo VARCHAR (255)
    fecha_registro = models.DateTimeField(auto_now_add=True) # fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP

    class Meta:
        db_table = 'procesos'
        verbose_name = "Proceso"
        verbose_name_plural = "Procesos"

    def __str__(self):
        return f"Proceso #{self.id_proceso} {self.id_expediente.id_expediente} - {self.id_tproceso.nombre}"
    



# --------------------------------------------------------------------# Modelo para documento

#class Documento(models.Model):
#    titulo = models.CharField(max_length=100)
#    archivo = models.FileField(upload_to='documentos/')
#    imagen = models.ImageField(upload_to='imagenes/', blank=True, null=True)
#
#   def __str__(self):
#        return self.titulo
